export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "About Me",
  headline: "random words",
  description: "random words",
  buttonLabel: "Contact Me",
  imgStart: false,
  img: require("./random.jpg").default,
  alt: "Random",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "coursework",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Part 2",
  headline: "random words",
  description: "random words",
  buttonLabel: "Contact Me",
  imgStart: true,
  img: require("./random2.jpg").default,
  alt: "Random2",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "timeline",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Part 3",
  headline: "random words",
  description: "random words",
  buttonLabel: "Contact Me",
  imgStart: false,
  img: require("./random3.jpg").default,
  alt: "Random3",
  dark: false,
  primary: false,
  darkText: true,
};
